#!/usr/bin/env python3
"""Genera seed/private/piloto/renombres.json: mapa original -> ficticio.

Reglas: consistencia total (mismo original siempre mismo ficticio),
fusión de duplicados (Corp/Corporation, MEX/MEXICO, 01 DE 03), giros
preservados, funcionales bancarios intactos. Determinista.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "apps" / "api"))

D = json.load(open("/tmp/mapeables.json", encoding="utf-8"))
# D: [[n, "CLAVE FUSION", [originales...]], ...] (ya ordenado por n desc)

FUNC_EXTRA = {"INTERNPAGO TDC": "PAGO TDC"}

# Typos/duplicados del banco: misma entidad real -> una sola clave.
MANUAL = {
    "DBM SUPPLY": "SUMINISTROS INDUSTRIALES BAJA",
    "PROCABLES MEXICO": "CABLEADOS DEL NORTE",
    "VELOCITY VEHICLES MEXICO": "AUTOMOTRIZ VELOCITY BAJA",
    "GRUPO GOURMET VIDANA RL CV": None,  # lo agarra restaurant por GOURMET
    "RCH CETYS": "RESTAURANTE CETYS UNIVERSITARIO",
    "SERTRES NORTE": "SERVICIOS TECNICOS DEL NORTE",
    "ARTREK CARGAS": "FLETES ARTREK BAJA",
    "GUACONMAR DISTRIBUCIONES SA CV": "DISTRIBUIDORA GUACONMAR NORTE",
    "GOBIERNO DEL ESTADO": "GOBIERNO ESTATAL",
    "INSTITUTO FONACOT": "FONDO CREDITO LABORAL",
    "WTHMXL CORPORATIVO SOCIEDAD POR ACCIONES": "TECNOLOGIA WTH NORTE",
    "WTHMXL CORPORATIVO": "TECNOLOGIA WTH NORTE",
    "RODIMA COMERCIALIZADORA": "COMERCIALIZADORA RODIMA NORTE",
    "LOS ARBOLITOS MEXICALI": "RESTAURANTE LOS ARBOLITOS",
    "MIYASI": "SUSHI MIYAGI",
    "JACK IN THE BOX 3055": "HAMBURGUESAS JACK NORTE",
}

ALIAS_FUSION = {
    "MAXIMIALNO URIBE REYES": "MAXIMILIANO URIBE REYES",
    "MAXIMILIANO URIBE": "MAXIMILIANO URIBE REYES",
    "MARIA FERENANDA VALENZUELA VEGA": "MARIA FERNANDA VALENZUELA VEGA",
    "ELEMENT FLEET MANAGEMENT CORP MEX": "ELEMENT FLEET MANAGEMENT CORP MEXICO",
}

# Conceptos de pago (no contrapartes): van a etiqueta funcional.
FUNC_CONCEPTO = [
    (r"^RENTA\b|PAGO .*RENTA|ARRENDAMIENTO", "ARRENDAMIENTO LOCAL"),
    (r"^HONORARIOS|HONO\b|HONO ", "HONORARIOS PROFESIONALES"),
    (r"^MAMA\b|^MAMI\b|MAMA SEMANA", "APOYO FAMILIAR"),
    (r"^ANTICIPO", "ANTICIPO A PROVEEDORES"),
    (r"^CUOTA\b", "CUOTA"),
    (r"^COMPENSACION", "COMPENSACION BANCARIA"),
    (r"^MANEJO REDES", "MARKETING REDES SOCIALES"),
    (r"RAMPA SPEED", "SERVICIO DE INSTALACION"),
    (r"^IMPRESIONES|^FOLIO IMPRES", "IMPRENTA DEL VALLE"),
    (r"^IMPLE APP", "DESARROLLO DE APP"),
    (r"^PAGO\b", "PAGO A PROVEEDOR"),
    (r"^GASTOS\b|^GASTOS ESCOLARES|^ESCUELA\b", "GASTOS"),
    (r"^SERVICIO\b", "SERVICIO"),
    (r"HONORARIOS", "HONORARIOS PROFESIONALES"),
]

PERSONAS_FIJAS = {
    "JOAN PEDRO URIBE RUIZ": "PEDRO PISTONES GARCIA",  # dueño -> identidad ficticia
    "LUIS BERENGUER IBARRONDO": "JUAN PEREZ LOMELI",
    "MARISOL HERNANDEZ IBARRA": "LAURA GOMEZ SALINAS",
    "LUIS MACIAS SEGURA": "CARLOS MENDOZA RUIZ",
    "MARIA FERENANDA VALENZUELA VEGA": "ANA SOFIA VALDEZ MORA",
    "GILBERTO GONZALEZ GARDEA": "MIGUEL TORRES AGUILAR",
    "JOSE ANTONIO ESPINOSA LOPEZ": "DAVID ESPINOZA LUNA",
    "ANDRES SEBASTIAN BEJARANO SOTO": "SERGIO BEJARANO SOTO",
    "CARLOS RAMOS VERDUGO": "RAUL RAMOS VERDUGO",
    "YADIRA PINZON": "ELENA PINEDA ROJAS",
    "MARIA FERNANDA VALENZUELA VEGA": "MARIANA VALDEZ MORA",
    "MARICELA CASTRO OJEDA": "KARLA CASTRO OJEDA",
    "LUIS FERNANDO REYES RUIZ PALACIOS": "FERNANDO RUIZ PALACIOS",
    "JULIO CESAR JUNGO SANCHEZ": "JULIO JUNGO SALINAS",
    "EFRAIN AGUILAR CEVALLOS": "EFRAIN AGUILAR CERVANTES",
    "COTTY DUARTE": "DANIELA DUARTE LOPEZ",
    "CHRISTIAN JOSUE FERNANDEZ CARRANCO": "CRISTIAN FERNANDEZ CARRANCO",
    "SOL AURORA CORTEZ AUDELO": "AURORA CORTEZ AUDELO",
    "MAXIMILIANO URIBE REYES": "DIEGO PISTONES GARCIA",
    "RIVERA SEPULVEDA MARIO": "MARIO RIVERA SEPULVEDA",
    "JOSE JIAN,SAMANIEGO/DAVILA": "JORGE SAMANIEGO DAVILA",
    "ANDREA GUADALUPE NIEBLA": "ANDREA NIEBLA ROBLES",
    "DENTISTA OCTAVIO REYES": "DENTISTA RICARDO PAZ",
}

PERSONAS_POOL = ["FERNANDO CASTRO LEON", "ROBERTO DIAZ FUENTES",
                 "ALEJANDRO VARGAS RIOS", "DANIEL SOTO MARQUEZ",
                 "EDUARDO REYES CAMACHO", "JORGE LARA MONTES",
                 "OSCAR NAVA QUINTERO", "PABLO IBARRA SERRANO",
                 "RICARDO MORA DELGADO", "ARTURO SALGADO VEGA",
                 "MARTA JIMENEZ FLORES", "PATRICIA RUIZ CARDENAS",
                 "VERONICA LOPEZ MATA", "GABRIELA FIERRO LAMAS",
                 "ADRIANA SOLIS BRAVO", "MONICA VILLA REYES",
                 "CESAR ORTIZ PEREZ", "HUGO BLANCO TERAN",
                 "IVAN ZARATE CORONA", "MARIO DUARTE SIERRA",
                 "HECTOR LUNA VILLALOBOS", "ALFREDO REYES DOMINGUEZ",
                 "ARMANDO CRUZ MELENDEZ", "ENRIQUE FLORES SOTO",
                 "FELIPE GONZALEZ IBARRA", "GUSTAVO HERRERA CAMPOS",
                 "JAVIER MENDOZA TORRES", "LORENZO AGUIRRE VELAZQUEZ",
                 "NICOLAS ROJAS FUENTES", "RAMON DELGADO MORA",
                 "SANTIAGO VEGA LUNA", "TOMAS SILVA ROSAS",
                 "VICTOR CANO MARIN", "ERNESTO PAREDES SOTO",
                 "CARMEN ORTEGA SALAS", "DOLORES MEDINA CASTRO",
                 "ESPERANZA ROCHA DIAZ", "FRANCISCA LEON VARGAS",
                 "GLORIA MIRELES SANTOS", "HILDA CUEVAS RAMOS",
                 "IRMA SALAZAR ORTIZ", "JUANA PEREZ HERNANDEZ",
                 "LOURDES CAMPOS RUIZ", "MARTHA ELENA VIDAL TORRES"]

# (patron regex, pool de ficticios) en orden de prioridad
GIROS = [
    ("REFACC|REFAC |DAR MEXICALI|QPOS|AUTOPART|AUTO PARTES|VOLKS|BRAKE|NAPA|AUTOP|AUTOCARM|AUTOZONE|AUTOEQUIP|GONHER|GONHERMEX|APYMSA|RAD AM",
     ["REFACCIONARIA DEL NORTE", "REFACCIONES DEL VALLE", "AUTOPARTES MEXICALI",
      "REFACCIONARIA SAN PEDRO", "AUTOPARTES DEL PACIFICO", "REFACCIONES VISTA HERMOSA",
      "AUTOPARTES CALAFIA", "REFACCIONARIA ENSENADA", "AUTOPARTES FRONTERA",
      "REFACCIONES CACHANILLA", "AUTOPARTES INDUSTRIAL", "REFACCIONARIA EL GALLO",
      "AUTOPARTES SANTA FE", "REFACCIONES PUENTE", "AUTOPARTES MODERNO",
      "REFACCIONARIA LA CURVA", "AUTOPARTES EJIDO PUEBLA", "REFACCIONES SAN LUIS",
      "AUTOPARTES COLONIA NUEVA", "REFACCIONARIA EL CRUCERO", "AUTOPARTES PEDREGAL",
      "REFACCIONES SOLIDARIDAD", "AUTOPARTES PORTALES", "REFACCIONARIA SAN MARCOS"]),
    ("REST|TACOS|MARISCOS|GOURMET|PIZZA|BUFFALO|DENNY|IHOP|SUSHI|BURGER|CARNITAS|MANGO ROA|THRIFTY|YAMI HOUS|JING WAHX|RUTA TR|LUCKY|MANG$|COMIDA|RESTAURANTE|CAFETERIA|LONCHERIA",
     ["RESTAURANTE EL FARO", "TACOS EL VALLE", "MARISCOS LA BAJA", "PIZZERIA NAPOLI",
      "RESTAURANTE CASA VERDE", "COCINA DOÑA ROSA", "TACOS DE CANASTA MXL",
      "RESTAURANTE PUERTO NUEVO", "FONDA LA ESQUINA", "SUSHI KAIYO",
      "HAMBURGUESAS EL ROBLE", "RESTAURANTE VILLA MARINA", "CAFETERIA PUNTO NORTE",
      "TACOS AL VAPOR CENTRO", "RESTAURANTE LOS ARCOS", "MARISCOS EL TIMON",
      "RESTAURANTE LA MISION", "TACOS EL TRAILERO", "MARISCOS PUERTO ABRIGO",
      "FONDA SANTA CLARA", "RESTAURANTE EL MIRADOR", "PIZZERIA ROMA MXL",
      "TACOS EL CHINO", "MARISCOS BAHIA BLANCA", "RESTAURANTE DON BETO"]),
    ("STARBUCKS|CAFE NEGRITA|CAFE |COFFEE", ["CAFETERIA LUNA LLENA", "CAFE BOLA DE ORO"]),
    ("GASOL|GAS |SERVICENTRO|ESTACION |BOMBAS DE GASOLINA",
     ["GASOLINERA EL CAMINO", "GAS DEL VALLE", "SERVICENTRO FRONTERA",
      "GASOLINERA SANTA ISABEL", "COMBUSTIBLES DEL NORTE",
      "GASOLINERA LA CURVA", "SERVICENTRO EJIDAL", "COMBUSTIBLES CALAFIA",
      "GASOLINERA PUENTE PALOMAS", "SERVICENTRO LOMAS", "GAS EXPRESS VALLE",
      "COMBUSTIBLES SANTA FE", "GASOLINERA EL REFUGIO", "SERVICENTRO MODERNO",
      "GAS DEL DESIERTO", "COMBUSTIBLES LA MISION"]),
    ("\\bES\\b|\\bEST\\b|\\bBOX\\b",
     ["ESTACION SERVICIO CENTRO", "ESTACION SERVICIO LOMAS",
      "MINISUPER BOX NORTE", "ESTACION SERVICIO CALAFIA"]),
    ("LLANTAS|RINES|RADEC", ["LLANTAS DEL DESIERTO", "LLANTAS Y RINES MXL"]),
    ("KONFIO|FINTECH",
     ["FINANCIERA PULSO", "CREDITO NEGOCIOS BAJA"]),
    ("HEY BANCO", ["BANCO DIGITAL FRONTERA"]),
    ("\\bCFE\\b", ["ENERGIA ELECTRICA ESTATAL"]),
    ("RADIORAMA|\\bRADIO\\b|PUBLICIDAD|PUNTO CLAVE",
     ["RADIO FRONTERA", "AGENCIA PUBLICIDAD VALLE"]),
    ("FONACOT|INFONAVIT", ["FONDO CREDITO LABORAL"]),
    ("GUACONMAR",
     ["DISTRIBUIDORA DEL DESIERTO", "DISTRIBUIDORA MAYORISTA BAJA"]),
    ("DIAGN.*NISSAN|AGENCIA.*AUTO|NISSAN",
     ["AGENCIA AUTOMOTRIZ NIPONA", "AGENCIA DEL VALLE MOTORS"]),
    ("SEARS|COPPEL|ELEKTRA|DEPARTAMENTAL|SUBURBIA|LIVERPOOL",
     ["TIENDA SEARS DEL VALLE", "COPPEL FRONTERA", "ELEKTRA CACHANILLA"]),
    ("ATT\\b|TELCEL|MOVISTAR|TELEFONIA|CELULAR",
     ["TELEFONIA ATT FRONTERA", "TELCEL DEL VALLE", "RECARGAS CELULAR MXL"]),
    ("RECAUDACION|TESORERIA|PREDIAL|TENENCIA",
     ["TESORERIA DEL ESTADO", "PREDIAL MUNICIPAL MXL"]),
    ("LUBRICANTES|LUBRICAN|\\bACEITE\\b|CAM ACEITE", ["LUBRICANTES EXPRESS", "ACEITES DEL VALLE"]),
    ("LOS ARBOLITOS|MIYASI|TUTTI FRUTTI",
     ["RESTAURANTE LOS ARBOLITOS", "SUSHI MIYAGI", "HELADERIA TUTTI VALLE",
      "RESTAURANTE ARBOLEDAS", "SUSHI ORIENTAL MXL", "HELADERIA LA MICHOACANA MXL",
      "RESTAURANTE EL OLIVO"]),
    ("CAFFENIO", ["CAFETERIA CAFFENIO NORTE", "CAFE EXPRESO BAJA"]),
    ("AYUNTAMIENTO", ["AYUNTAMIENTO DE MEXICALI", "GOBIERNO MUNICIPAL FRONTERA"]),
    ("SINDICATO", ["SINDICATO UNICO DE TRABAJADORES"]),
    ("BIRLOS|TORNILLOS", ["TORNILLERIA EL ROBLE", "BIRLOS Y TORNILLOS DEL NORTE"]),
    ("CHRYSLER|DISTRIBUID.*AUT|DIST AUT", ["AGENCIA AUTOMOTRIZ FRONTERA"]),
    ("OMNIPAGOS|PAGOS EN LINEA", ["PASARELA OMNIPAGOS MX", "COBRO DIGITAL OMNIPAGOS"]),
    ("VACACIONES|VIAJES|VOLARIS|AEROMEXICO", ["AGENCIA VIAJES FRONTERA"]),
    ("FAR GUAD|FARMACIA GUAD", ["FARMACIA GUADALAJARA NORTE"]),
    ("A LA MEXICANA", ["RESTAURANTE A LA MEXICANA"]),
    ("WTHMXL", ["TECNOLOGIA WTH NORTE", "SOLUCIONES DIGITALES WTH"]),
    ("RODIMA", ["COMERCIALIZADORA RODIMA NORTE"]),
    ("CENTRO MEX", ["CENTRO CAMBIARIO MEXICO"]),
    ("325 MEXICALI", ["COMERCIO 325 MEXICALI"]),
    ("TEF RECIBIDO|TRANSFERENCIA RECIBIDA", ["TRANSFERENCIA RECIBIDA"]),
    ("URIBOT", ["SOFTWARE URIBOT"]),
    ("PARAMAMA|DICALSI|FLORAC|BONAPRIME|LUMAGGS|CENTRO MEXICO|REP PUERTA|\\bMAT\\b|MATERIALES",
     ["COMERCIALIZADORA DEL NORTE", "DISTRIBUIDORA CACHANILLA",
      "COMERCIO MAYORISTA BAJA", "MATERIALES DEL VALLE",
      "PROVEEDORA INDUSTRIAL MXL", "COMERCIAL SANTA FE",
      "DISTRIBUIDORA PORTALES", "COMERCIO FRONTERA NORTE"]),
    ("OXXO|WAL MART|SMART FINAL|LIVERPOOL|SUCURSAL|DILLARDS|BODEGA|COSTERO|TIENDA|LA BARRA|STAY HOME",
     ["TIENDA LA ESQUINA", "SUPER DEL BARRIO", "MINISUPER FRONTERA",
      "TIENDA DEPARTAMENTAL CENTRO", "SUPER AHORRO NORTE",
      "SUPER LA FRONTERA", "MINISUPER SANTA FE", "TIENDA EL FARO",
      "SUPER VALLE DORADO", "MINISUPER LOMAS", "TIENDA EL ROBLE",
      "SUPER CALAFIA", "MINISUPER PORTALES", "TIENDA SANTA CLARA",
      "SUPER MODERNO MXL", "MINISUPER VISTA HERMOSA"]),
    ("FLEET|FLOTILLA|PROCABLES|SERTRES|DBM SUPPLY|GIPAAC|TRANSPORTE|FLETE|CARGAS|VELOCITY|TRANSPART|TRANS POT",
     ["FLOTILLAS DEL PACIFICO", "TRANSPORTES BAJA NORTE", "LOGISTICA FRONTERA",
      "FLETES EL RAPIDO", "GRUPO GASTRONOMICO VALLE", "INFRAESTRUCTURA PENINSULAR",
      "TRANSPORTES EJIDATARIOS", "CARGA PESADA MXL", "FLOTILLA COMERCIAL NORTE",
      "DISTRIBUIDORA PENINSULA", "SUMINISTROS INDUSTRIALES BAJA",
      "TRANSPORTES EL CENTINELA", "LOGISTICA DEL DESIERTO", "FLETES URIAS",
      "GRUPO ALIMENTICIO NOROESTE", "TRANSPORTES SAN FELIPE", "CARGA EXPRESS BAJA",
      "FLOTILLAS UNIDAS MXL", "DISTRIBUIDORA EL MAYORISTA", "SERVICIOS LOGISTICOS LAGUNA"]),
    ("SEGUROS|QUALITAS|ASEGURADORA", ["SEGUROS ATLAS", "ASEGURADORA DEL NORTE"]),
    ("NETPAY|PAYCLIP|MERPAGO|CLIP |BPK|TCONE|AGREGADOR|CELLSHOP",
     ["AGREGADOR PAGOS MX", "PASARELA COBRO NORTE", "TERMINAL PAGOS BAJA",
      "COBRO DIGITAL FRONTERA", "PAGOS EN LINEA BAJA", "TERMINAL MOVIL MXL",
      "AGREGADOR COMERCIO NORTE", "COBRO CON TARJETA BAJA", "PASARELA TPE FRONTERA",
      "PAGOS RECURRENTES NORTE", "TERMINAL PUNTO VENTA MX", "COBRO EXPRESS BAJA",
      "AGREGADOR UNIVERSAL PAGOS", "PASARELA SEGURA NORTE", "TERMINAL INTELIGENTE MXL",
      "COBRO FACIL FRONTERA", "PAGOS MOVILES PENINSULA", "TERMINAL NUBE BAJA",
      "AGREGADOR TOTAL COBROS", "PASARELA FRONTERIZA MX"]),
    ("FARM |FARMACIA|DERMAMORE", ["FARMACIA SAN RAFAEL", "FARMACIA DEL CENTRO", "FARMACIA GUADALUPANA MXL",
      "FARMACIA LA BAJA", "FARMACIA SANTA FE NORTE", "FARMACIA EL AHORRO BAJA"]),
    ("DENTISTA|CONSULTORIO|MEDICO|DOCTOR|CLINICA", ["CONSULTORIO MEDICO LOMAS", "CLINICA SANTA FE", "CONSULTORIO DENTAL SONRISA",
      "CLINICA FAMILIAR DEL VALLE", "CONSULTORIO MEDICO SANTA FE"]),
    ("GOBIERNO|ESTADO|INTERNA DE|GARITA|ANAM ", ["GOBIERNO ESTATAL", "ADUANA FRONTERA", "RECAUDACION MUNICIPAL MXL",
      "OFICINA FISCAL DEL ESTADO", "REGISTRO PUBLICO BAJA"]),
    ("HIIT PRO", ["GIMNASIO ATHLOS", "CENTRO FITNESS CACHANILLA"]),
    ("ESCUELA|CETYS|COLEGIO|UNIVERSIDAD|RCH ",
     ["UNIVERSIDAD DEL VALLE", "COLEGIO FRONTERA", "INSTITUTO TECNICO BAJA",
      "PREPARATORIA FEDERAL MXL", "COLEGIO BILINGUE NORTE",
      "UNIVERSIDAD POLITECNICA BAJA", "ACADEMIA DEPORTIVA CACHANILLA"]),
    ("NOTARIA", ["NOTARIA PUBLICA 4"]),
    ("SUZUKI|CARM MOTORS|MOTORS|VEHICLES|VEHICULOS", ["MOTOS DEL DESIERTO", "AUTOMOTRIZ PENINSULAR"]),
    ("TRUPER|FERRETERIA|TLAPALERIA", ["FERRETERIA EL TORNILLO", "TLAPALERIA CENTRO"]),
    ("STEREN|ELECTRONICA|TONERS|ELEC FELIX", ["ELECTRONICA ESTRELLA", "TONERS Y OFICINA"]),
    ("RONSA|EQUIPO|REFRIGERACION|CLIMAS", ["EQUIPOS Y REFRIGERACION BAJA", "CLIMAS DEL NORTE"]),
    ("PROCONSA|CONSTRUCTORA|OBRA|CEMENTO", ["CONSTRUCTORA PENINSULAR", "OBRAS Y CAMINOS BAJA"]),
    ("OASA|ORGANISMO|AGUA|CESP", ["ORGANISMO DE AGUA MXL"]),
    ("LAVANDERIA|TINTORERIA", ["LAVANDERIA BURBUJAS"]),
    ("PELUQ|BARBERIA|ESTETICA|SPA |MAJA SPW", ["BARBERIA EL NAVAJAZO", "ESTETICA UNISEX CENTRO"]),
    ("FLORERIA|\\bFLOR\\b", ["FLORERIA LAS DALIAS", "FLORERIA JARDIN BAJA"]),
    ("PARKING|ESTACIONAMIENTO", ["ESTACIONAMIENTO CENTRO"]),
    ("PARFUM|PERFUME|FRENCH", ["PERFUMERIA ESENCIA"]),
    ("GAS GRUGAS|PAGANDO", ["PAGOS SERVICIOS MX"]),
    ("ZTL|RUSH", ["SERVICIOS DIGITALES RUSH"]),
    ("ALARMAS|SEGURIDAD|PREMIER", ["ALARMAS Y SEGURIDAD NORTE"]),
]

BIZ_KEYWORDS = re.compile(
    r"SA\b|CV\b|CORP|CIA|GRUPO|REST|TACOS|GASOL|OXXO|STARBUCKS|FARM|AUTO|REFACC|"
    r"SEGUROS|GOBIERNO|ESCUELA|NOTARIA|TALLER|FLETE|HOTEL|BANCO|TIENDA|MARKET|"
    r"CLINICA|LABORATORIO|PAGO|COBRO|VENTA|COMPRA| \*|PAY|NET|CLIP|MXL|M vl\b", re.I)


def es_persona(clave, originales):
    if clave in PERSONAS_FIJAS:
        return True
    for o in originales:
        toks_o = set(re.split(r"[^A-Z0-9]+", o.upper()))
        # Tokens societarios EXACTOS (el \bSA cazaba "SANCHEZ"/"SANTOS").
        if toks_o & {"SA", "CV", "SAS", "CORP", "CIA", "GRUPO", "RL", "INC",
                     "LLC", "SRL"}:
            return False
    if BIZ_KEYWORDS.search(clave):
        return False
    toks = [t for t in re.split(r"\s+", clave) if t.isalpha()]
    return len(toks) >= 2


def main():
    mapa, usados, ipers = {}, set(), [0]

    def toma(pool_idx):
        pool = pools[pool_idx]
        assert pool, f"pool agotado giro {GIROS[pool_idx][0][:30]}"
        nombre = pool.pop(0)
        assert nombre not in usados
        usados.add(nombre)
        return nombre

    def persona():
        while ipers[0] < len(PERSONAS_POOL) * 2:
            nombre = PERSONAS_POOL[ipers[0] % len(PERSONAS_POOL)]
            ipers[0] += 1
            if nombre not in usados:
                usados.add(nombre)
                return nombre
        raise AssertionError("pool de personas agotado")

    detalle = []
    por_persona = []
    pools = {i: list(p) for i, (_, p) in enumerate(GIROS)}
    # MANUAL manda: sus nombres salen de los pools para no duplicar.
    _tomados = {v for v in MANUAL.values() if v}
    usados |= _tomados
    for i in pools:
        pools[i] = [x for x in pools[i] if x not in _tomados]

    def guarda(clave, nuevo, n, originales, regla):
        """Alias puede colisionar: fusiona n y originales."""
        if clave in mapa:
            mapa[clave]["n"] += n
            mapa[clave]["originales"] += [o for o in originales
                                          if o not in mapa[clave]["originales"]]
        else:
            mapa[clave] = {"nuevo": nuevo, "n": n, "originales": originales,
                           "regla": regla}
    for n, k, originales in D:
        clave = k[1] if isinstance(k, list) else k
        clave = ALIAS_FUSION.get(clave, clave)
        funcional = next((et for pat, et in FUNC_CONCEPTO
                          if re.search(pat, clave)), None)
        if funcional:
            guarda(clave, funcional, n, originales, "funcional")
            continue
        if clave in FUNC_EXTRA:
            guarda(clave, FUNC_EXTRA[clave], n, originales, "funcional")
            continue
        if clave in PERSONAS_FIJAS:
            guarda(clave, PERSONAS_FIJAS[clave], n, originales, "persona-fija")
            usados.add(PERSONAS_FIJAS[clave])
            continue
        if clave in MANUAL and MANUAL[clave]:
            guarda(clave, MANUAL[clave], n, originales, "manual")
            usados.add(MANUAL[clave])
            continue
        asignado = None
        for i, (pat, _) in enumerate(GIROS):
            if re.search(pat, clave):
                asignado = toma(i)
                regla = f"giro:{pat[:24]}"
                break
        if asignado is None:
            if es_persona(clave, originales):
                por_persona.append((n, clave, originales))
                # se asigna después (para ver cuántas hay)
                detalle.append((n, clave, originales, "persona-pendiente"))
                continue
            detalle.append((n, clave, originales, "!!! SIN REGLA"))
            continue
        guarda(clave, asignado, n, originales, regla)
    print(f"mapeados: {len(mapa)}")
    print(f"personas detectadas: {len(por_persona)}")
    for n, clave, originales in por_persona:
        guarda(clave, persona(), n, originales, "persona-pool")
    out = Path(REPO) / "seed/private/piloto/renombres.json"
    out.write_text(json.dumps(mapa, ensure_ascii=False, indent=1),
                   encoding="utf-8")
    print(f"escrito {out} ({len(mapa)} entradas)")
    for n, clave, originales, marca in detalle:
        print(f"{n:4d} {clave[:55]} <- {originales[0][:50]} {marca}")


if __name__ == "__main__":
    main()
