"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { fetchDashboard } from "@/lib/api";
import type { DashboardDailyPoint, DashboardData, DashboardGroup, DashboardTransaction, ReceivableItem } from "@/lib/types";
import styles from "./cards.module.css";

type Filter = "today" | "all" | "attention" | "healthy";
type Tone = "urgent" | "watch" | "positive" | "neutral";
type CardDef = { id: string; category: string; priority: number; tone: Tone; wide?: boolean; node: ReactNode };

const currency = new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN", maximumFractionDigits: 0 });
const shortDate = new Intl.DateTimeFormat("es-MX", { day: "2-digit", month: "short" });
const monthName = new Intl.DateTimeFormat("es-MX", { month: "short", year: "numeric", timeZone: "UTC" });
const fullDate = new Intl.DateTimeFormat("es-MX", { day: "2-digit", month: "long", year: "numeric", timeZone: "UTC" });
const number = (value: unknown) => Number(value ?? 0);
const money = (value: unknown) => currency.format(number(value));
const percent = (value: unknown, digits = 1) => `${(number(value) * 100).toFixed(digits)}%`;
const signedPercent = (value: unknown) => `${number(value) >= 0 ? "+" : ""}${percent(value)}`;
const displayMonth = (month: string) => monthName.format(new Date(`${month}-01T00:00:00Z`)).replace(" de ", " ").toUpperCase();
const labelFor = (value: string) => ({ nomina: "Nómina", software: "Software", servicios: "Servicios", impuestos: "Impuestos", proveedores_materiales: "Proveedores", por_clasificar: "Otros gastos", spei_enviado: "Transferencias", domiciliacion: "Pagos automáticos", comision: "Comisiones", iva_comision: "IVA de comisiones" }[value] ?? value.replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase()));

function Icon({ name, size = 19 }: { name: string; size?: number }) {
  const paths: Record<string, ReactNode> = {
    receipt: <><path d="M6 3h12v18l-3-2-3 2-3-2-3 2Z"/><path d="M9 8h6M9 12h6M9 16h3"/></>,
    wallet: <><path d="M3 6h16a2 2 0 0 1 2 2v11H5a2 2 0 0 1-2-2Z"/><path d="M3 8V6a3 3 0 0 1 3-3h11v3M16 12h5"/></>,
    bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,
    moon: <path d="M20 15.2A8 8 0 0 1 8.8 4 8.5 8.5 0 1 0 20 15.2Z"/>,
    sun: <><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></>,
    arrow: <><path d="M5 12h14M14 7l5 5-5 5"/></>,
    dots: <><circle cx="5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1" fill="currentColor" stroke="none"/></>,
  };
  return <svg aria-hidden="true" viewBox="0 0 24 24" width={size} height={size} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name] ?? paths.wallet}</svg>;
}

function BanorteLogo() {
  return <a className={styles.banorteLogo} href="/" aria-label="Banorte MiNorte inicio"><svg aria-hidden="true" viewBox="0 0 54 40"><path d="M3 11.5 18.5 3H37l-15.5 8.5H3Z"/><path d="m17.2 15.7 15.6-8.5h18.3l-15.5 8.5H17.2Z"/><path d="m3 20 15.5-8.5H37L21.5 20H3Z"/><path d="m17.2 24.2 15.6-8.5h18.3l-15.5 8.5H17.2Z"/><path d="m3 28.4 15.5-8.5H37l-15.5 8.5H3Z"/><path d="m17.2 32.6 15.6-8.5h18.3l-15.5 8.5H17.2Z"/></svg><span><b>BANORTE</b><small>MiNorte para empresas</small></span></a>;
}

function Chip({ children, tone = "neutral" }: { children: ReactNode; tone?: Tone }) { return <span className={`${styles.chip} ${styles[`chip_${tone}`]}`}>{children}</span>; }
function Card({ title, eyebrow, action, children, className = "" }: { title: string; eyebrow?: string; action?: ReactNode; children: ReactNode; className?: string }) { return <article className={`${styles.card} ${className}`}><header className={styles.cardHeader}><div>{eyebrow ? <p className={styles.eyebrow}>{eyebrow}</p> : null}<h2>{title}</h2></div>{action ?? <button className={styles.iconButton} aria-label={`Más opciones de ${title}`}><Icon name="dots"/></button>}</header>{children}</article>; }

function Sparkline({ values, color = "#eb0029" }: { values: number[]; color?: string }) {
  const safe = values.length > 1 ? values : [values[0] ?? 0, values[0] ?? 0]; const max = Math.max(...safe); const min = Math.min(...safe);
  const coordinates = safe.map((value, index) => ({ x: 3 + index / (safe.length - 1) * 94, y: 33 - (value - min) / Math.max(max - min, 1) * 27 })); const points = coordinates.map(({ x, y }) => `${x},${y}`).join(" "); const last = coordinates.at(-1)!;
  return <svg className={styles.sparkline} viewBox="0 0 100 38" preserveAspectRatio="none" aria-label="Tendencia real por mes"><polygon points={`3,37 ${points} 97,37`} fill={color} opacity=".09"/><polyline points={points} fill="none" stroke={color} strokeWidth="2.2" vectorEffect="non-scaling-stroke"/><circle cx={last.x} cy={last.y} r="2.4" fill={color}/></svg>;
}

function MetricCard({ label, value, change, values, tone }: { label: string; value: string; change: string; values: number[]; tone: Tone }) { const color = tone === "urgent" ? "#eb0029" : tone === "watch" ? "#d97706" : "#12805c"; return <Card title={label} action={<Chip tone={tone}>{change}</Chip>}><div className={styles.metricValue}>{value}</div><p className={styles.muted}>Cambio frente al mes anterior</p><Sparkline values={values} color={color}/></Card>; }
function CashCard({ value, runway, values }: { value: string; runway: number; values: number[] }) {
  const safeValues = values.length ? values : [0]; const opening = safeValues[0]; const current = safeValues.at(-1) ?? 0; const target = 18; const safeRunway = Math.max(0, Math.min(target, Math.round(runway)));
  return <Card title="Efectivo disponible" action={<Chip tone={runway < 15 ? "urgent" : "positive"}>{Math.round(runway)} días</Chip>}>
    <div className={styles.metricValue}>{value}</div>
    <div className={styles.cashChartHeader}><span>Evolución de caja</span><strong className={current >= opening ? styles.positiveText : ""}>{current >= opening ? "+" : ""}{money(current - opening)} este periodo</strong></div>
    <Sparkline values={safeValues} color={runway < 15 ? "#eb0029" : "#12805c"}/>
    <div className={styles.cashValues}><span>Inicio <b>{money(opening)}</b></span><span>Hoy <b>{money(current)}</b></span></div>
    <div className={styles.runwayVisual} aria-label={`La caja cubre ${safeRunway} de ${target} días recomendados`}><div>{Array.from({ length: target }, (_, index) => <i key={index} className={index < safeRunway ? styles.runwayActive : ""}/>)}</div><span>{safeRunway} de {target} días recomendados</span></div>
  </Card>;
}
function Ring({ value, label }: { value: number; label: string }) { const safe = Math.max(0, Math.min(100, value)); return <div className={styles.ring} style={{ background: `conic-gradient(#eb0029 ${safe * 3.6}deg, #edf0f2 0deg)` }}><div><strong>{Math.round(safe)}%</strong><span>{label}</span></div></div>; }

function AreaChart({ items }: { items: DashboardDailyPoint[] }) {
  const safe = items.length > 1 ? items : [...items, ...(items.length ? [items[0]] : [])]; let income = 0; let expenses = 0;
  const incomeValues = safe.map((item) => (income += number(item.income))); const expenseValues = safe.map((item) => (expenses += number(item.expenses))); const max = Math.max(...incomeValues, ...expenseValues, 1);
  const points = (values: number[]) => values.map((value, index) => `${5 + index / Math.max(values.length - 1, 1) * 610},${165 - value / max * 135}`).join(" "); const incomePoints = points(incomeValues); const expensePoints = points(expenseValues);
  const dateLabel = (value?: string) => value ? shortDate.format(new Date(`${value}T12:00:00`)).toUpperCase() : "—"; const middle = safe[Math.floor(safe.length / 2)]?.date;
  return <div className={styles.areaWrap}><div className={styles.legend}><span><i className={styles.redDot}/>Ingresos</span><span><i className={styles.grayDot}/>Gastos</span></div><svg className={styles.area} viewBox="0 0 620 190" preserveAspectRatio="none" aria-label="Ingresos y gastos acumulados del mes"><g className={styles.gridLines}><path d="M5 30H615M5 75H615M5 120H615M5 165H615"/></g><polygon points={`5,165 ${incomePoints} 615,165`} fill="#eb0029" opacity=".11"/><polyline points={incomePoints} fill="none" stroke="#eb0029" strokeWidth="3" vectorEffect="non-scaling-stroke"/><polyline points={expensePoints} fill="none" stroke="#596069" strokeWidth="2" vectorEffect="non-scaling-stroke"/><g className={styles.axis}><text x="5" y="187">{dateLabel(safe[0]?.date)}</text><text x="285" y="187">{dateLabel(middle)}</text><text x="565" y="187">{dateLabel(safe.at(-1)?.date)}</text></g></svg></div>;
}

function Bars({ values, labels }: { values: number[]; labels: string[] }) { const max = Math.max(...values, 1); return <div className={styles.bars}>{values.map((value, index) => <div className={styles.barItem} key={`${labels[index]}-${index}`}><div className={styles.barTrack}><div className={`${styles.bar} ${index === values.length - 1 ? styles.barHot : ""}`} style={{ height: `${Math.max(8, value / max * 100)}%` }}/></div><span>{labels[index]}</span></div>)}</div>; }
function HorizontalBars({ items }: { items: { label: string; value: number; display: string }[] }) { const max = Math.max(...items.map((item) => item.value), 1); return <div className={styles.hBars}>{items.map((item, index) => <div key={item.label}><div className={styles.barLabels}><span>{item.label}</span><strong>{item.display}</strong></div><div className={styles.hTrack}><span style={{ width: `${item.value / max * 100}%`, opacity: 1 - index * .12 }}/></div></div>)}</div>; }

function DonutBreakdown({ groups }: { groups: DashboardGroup[] }) {
  const colors = ["#eb0029", "#34383e", "#9da4ac", "#d9dde1"]; const top = groups.slice(0, 3); const otherAmount = groups.slice(3).reduce((sum, item) => sum + number(item.amount), 0); const total = groups.reduce((sum, item) => sum + number(item.amount), 0);
  const visible = [...top, ...(otherAmount ? [{ name: "Otros", amount: String(otherAmount), percent: String(otherAmount / Math.max(total, 1)) }] : [])]; let cursor = 0; const stops = visible.map((item, index) => { const start = cursor; cursor += number(item.percent) * 100; return `${colors[index]} ${start}% ${cursor}%`; }).join(",");
  return <div className={styles.donutLayout}><div className={styles.donut} style={{ background: `conic-gradient(${stops || "#d9dde1 0 100%"})` }}><span>{money(total)}</span></div><div className={styles.donutLegend}>{visible.map((item, index) => <span key={item.name}><i style={{ background: colors[index] }}/>{labelFor(item.name)} <b>{percent(item.percent, 0)}</b></span>)}</div></div>;
}

function Aging({ items, asOf }: { items: ReceivableItem[]; asOf: string }) { const buckets = [0, 0, 0, 0]; const reference = new Date(`${asOf}T12:00:00`); items.forEach((item) => { const age = Math.max(0, Math.floor((reference.getTime() - new Date(item.issued_at).getTime()) / 86400000)); const index = age <= 15 ? 0 : age <= 30 ? 1 : age <= 60 ? 2 : 3; buckets[index] += number(item.amount_pending); }); const total = Math.max(buckets.reduce((sum, value) => sum + value, 0), 1); const labels = ["0–15 días", "16–30 días", "31–60 días", "+60 días"]; return <><div className={styles.aging}>{buckets.map((value, index) => <span key={labels[index]} style={{ width: `${value / total * 100}%` }}/>)}</div><div className={styles.agingLabels}>{buckets.map((value, index) => <span key={labels[index]}><i/>{labels[index]} <b>{money(value)}</b></span>)}</div><p className={styles.insight}>{items.length} facturas siguen pendientes de cobro.</p></>; }
function Timeline({ items }: { items: ReceivableItem[] }) { return <div className={styles.timeline}>{items.slice(0, 4).map((item) => <div key={item.id}><span className={`${styles.timelineDot} ${item.status === "overdue" ? styles.timelineWarn : ""}`}/><div><strong>{item.customer_name || "Cliente"}</strong><small>{item.due_date ? `Vence ${shortDate.format(new Date(item.due_date))}` : `Emitida ${shortDate.format(new Date(item.issued_at))}`}</small></div><b>{money(item.amount_pending)}</b></div>)}</div>; }
function Heatmap({ items }: { items: { date: string; count: number }[] }) { const max = Math.max(...items.map((item) => item.count), 1); return <div className={styles.heatmapWrap}><div className={styles.heatmap}>{items.map((item) => { const level = item.count ? Math.max(1, Math.ceil(item.count / max * 4)) : 0; return <span key={item.date} className={styles[`heat${level}`]} title={`${shortDate.format(new Date(`${item.date}T12:00:00`))}: ${item.count} movimientos`}/>; })}</div><div className={styles.heatLegend}><span>Menos actividad</span><i className={styles.heat1}/><i className={styles.heat2}/><i className={styles.heat3}/><i className={styles.heat4}/><span>Más</span></div></div>; }
function TransactionList({ items }: { items: DashboardTransaction[] }) { return <div className={styles.transactions}>{items.map((item) => { const incoming = item.type === "ingreso"; return <div key={item.id}><span className={`${styles.txIcon} ${incoming ? styles.txGreen : ""}`}><Icon name={incoming ? "wallet" : "receipt"}/></span><div><strong>{item.merchant || item.description}</strong><small>{labelFor(item.category)} · {shortDate.format(new Date(item.date)).toUpperCase()}</small></div><b className={incoming ? styles.positiveText : ""}>{incoming ? "+" : "−"}{money(item.amount)}</b></div>; })}</div>; }

function ActionCard({ variant, title, body, value, href }: { variant: "red" | "amber"; title: string; body: string; value: string; href?: string }) { return <Card title={title} eyebrow="REQUIERE ATENCIÓN" className={variant === "red" ? styles.actionRed : styles.actionAmber}><div className={styles.actionValue}>{value}</div><p className={styles.actionBody}>{body}</p>{href ? <a className={styles.primaryButton} href={href}>Resolver <Icon name="arrow" size={16}/></a> : <button className={styles.primaryButton}>Revisar <Icon name="arrow" size={16}/></button>}</Card>; }

function buildCards(data: DashboardData): CardDef[] {
  const summary = data.summary; const signal = (key: string) => number(data.signals[key]); const monthly = data.monthly; const salesGrowth = signal("crec_ventas"); const margin = signal("margen"); const runway = signal("runway_dias"); const latestDay = data.daily.at(-1)?.date ?? `${data.month}-28`; const alert = (rule: string) => data.alerts.find((item) => item.rule === rule);
  const counts = data.matches.counts; const matchTotal = Object.values(counts).reduce((sum, value) => sum + value, 0); const autoRate = matchTotal ? counts.auto / matchTotal : 0; const topCustomers = data.customers.slice(0, 4).map((item) => ({ label: item.name, value: number(item.amount), display: percent(item.percent, 0) })); const labels = monthly.map((item) => displayMonth(item.month).split(" ")[0]); const deductible = signal("pct_gasto_deducible"); const income = number(summary.ventas); const expenses = number(summary.gastos); const profit = number(summary.utilidad);
  return [
    { id: "receipts", category: "Fiscal", priority: 100, tone: "urgent", node: <ActionCard variant="red" title="Gastos sin factura" value={money(summary.gastos_sin_cfdi_total)} body={alert("sin_factura")?.detalle ?? `${summary.gastos_sin_cfdi_count} gastos necesitan una factura.`}/> },
    { id: "cash", category: "Flujo", priority: 98, tone: runway < 15 ? "urgent" : "positive", node: <CashCard value={money(summary.efectivo)} runway={runway} values={monthly.map((item) => number(item.cash))}/> },
    { id: "collections", category: "Cobranza", priority: 96, tone: "urgent", node: <ActionCard variant="amber" title="Cuentas por cobrar" value={money(summary.cuentas_por_cobrar)} body={alert("cuentas_por_cobrar")?.detalle ?? `${data.receivables.total} facturas siguen pendientes.`} href="/cobranza"/> },
    { id: "runway", category: "Liquidez", priority: 95, tone: runway < 15 ? "urgent" : "positive", node: <Card title="Días de caja" eyebrow="LIQUIDEZ"><div className={styles.ringRow}><Ring value={runway / 18 * 100} label="de 18 días"/><div><div className={styles.bigNumber}>{Math.round(runway)} días</div><p className={styles.muted}>Tiempo que la caja cubre el ritmo actual</p><Chip tone={runway < 15 ? "urgent" : "positive"}>{runway < 15 ? "Caja limitada" : "Caja estable"}</Chip></div></div><p className={styles.insight}>Con el gasto actual, el efectivo alcanza aproximadamente {Math.round(runway)} días.</p></Card> },
    { id: "flow", category: "Flujo", priority: 92, tone: profit >= 0 ? "positive" : "watch", wide: true, node: <Card title="Ingresos y gastos" eyebrow="MOVIMIENTO DEL MES" action={<Chip tone={profit >= 0 ? "positive" : "watch"}>{money(profit)} neto</Chip>}><div className={styles.chartSummary}><div><span>Entró</span><strong>{money(income)}</strong></div><div><span>Salió</span><strong>{money(expenses)}</strong></div><div><span>Diferencia</span><strong className={profit >= 0 ? styles.positiveText : ""}>{money(profit)}</strong></div></div><AreaChart items={data.daily}/></Card> },
    { id: "aging", category: "Cobranza", priority: 89, tone: "watch", node: <Card title="Edad de facturas pendientes" eyebrow="COBRANZA"><Aging items={data.receivables.items} asOf={latestDay}/></Card> },
    { id: "due", category: "Cobranza", priority: 88, tone: "watch", node: <Card title="Facturas por cobrar" eyebrow="PRÓXIMOS COBROS"><Timeline items={data.receivables.items}/></Card> },
    { id: "tax", category: "Fiscal", priority: 83, tone: "watch", node: <Card title="Impuestos estimados" eyebrow="CÁLCULO DEL MES"><div className={styles.matchHero}><strong>{money(summary.impuesto_estimado)}</strong><span>ISR estimado</span></div><div className={styles.payment}><span>IVA neto</span><b>{money(signal("iva_neto"))}</b></div><p className={styles.insight}>Estimación automática con los movimientos y CFDIs disponibles.</p></Card> },
    { id: "margin", category: "Rentabilidad", priority: 78, tone: margin >= 0 ? "positive" : "urgent", node: <MetricCard label="Margen del mes" value={percent(margin)} change={signedPercent(signal("margen_delta_pp"))} values={monthly.map((item) => number(item.margin) * 100)} tone={margin >= 0 ? "positive" : "urgent"}/> },
    { id: "sales", category: "Ventas", priority: 74, tone: salesGrowth >= 0 ? "positive" : "watch", node: <MetricCard label="Ingresos del mes" value={money(summary.ventas)} change={signedPercent(salesGrowth)} values={monthly.map((item) => number(item.sales))} tone={salesGrowth >= 0 ? "positive" : "watch"}/> },
    { id: "customers", category: "Ventas", priority: 68, tone: "neutral", node: <Card title="Principales clientes" eyebrow="DE DÓNDE ENTRA EL DINERO"><HorizontalBars items={topCustomers}/><p className={styles.insight}>{topCustomers[0]?.label ?? "Sin clientes"} aporta la mayor parte de los ingresos del mes.</p></Card> },
    { id: "categories", category: "Gastos", priority: 65, tone: "neutral", node: <Card title="¿En qué se gastó?" eyebrow="GASTOS POR TIPO"><DonutBreakdown groups={data.categories}/></Card> },
    { id: "deductible", category: "Fiscal", priority: 60, tone: deductible >= .9 ? "positive" : "watch", node: <Card title="Gastos con comprobante" eyebrow="ORDEN FISCAL"><div className={styles.matchHero}><strong>{percent(deductible, 0)}</strong><span>con CFDI</span></div><div className={styles.progress}><span style={{ width: `${Math.max(0, Math.min(100, deductible * 100))}%` }}/></div><p className={styles.insight}>La mayoría de los gastos ya tiene comprobante fiscal.</p></Card> },
    { id: "match", category: "Fiscal", priority: 58, tone: autoRate > .9 ? "positive" : "watch", node: <Card title="Movimientos conciliados" eyebrow="BANCO + CFDI"><div className={styles.matchHero}><strong>{percent(autoRate, 1)}</strong><span>automáticos</span></div><div className={styles.progress}><span style={{ width: `${autoRate * 100}%` }}/></div><div className={styles.threeStats}><span><b>{counts.auto}</b> listos</span><span><b>{counts.review}</b> por revisar</span><span><b>{counts.unmatched}</b> sin CFDI</span></div></Card> },
    { id: "months", category: "Ventas", priority: 52, tone: salesGrowth >= 0 ? "positive" : "watch", node: <Card title="Ingresos por mes" eyebrow="HISTORIAL REAL"><Bars values={monthly.map((item) => number(item.sales))} labels={labels}/><div className={styles.deltaLine}><strong>{signedPercent(salesGrowth)}</strong><span>frente al mes anterior</span></div></Card> },
    { id: "transactions", category: "Operación", priority: 44, tone: "neutral", wide: true, node: <Card title="Movimientos recientes" eyebrow="ACTIVIDAD BANCARIA" action={<Chip>{data.recent_transactions.length} recientes</Chip>}><TransactionList items={data.recent_transactions}/></Card> },
    { id: "activity", category: "Operación", priority: 38, tone: "neutral", node: <Card title="Actividad bancaria" eyebrow="ÚLTIMOS 35 DÍAS"><Heatmap items={data.activity}/><div className={styles.deltaLine}><strong>{data.activity.reduce((sum, item) => sum + item.count, 0)}</strong><span>movimientos en 35 días</span></div></Card> },
    { id: "payroll", category: "Gastos", priority: 35, tone: "neutral", node: <Card title="Nómina identificada" eyebrow="PERSONAL"><div className={styles.matchHero}><strong>{money(signal("masa_salarial_estimada"))}</strong><span>este mes</span></div><p className={styles.insight}>Total detectado en movimientos bancarios con concepto de nómina.</p></Card> },
  ];
}

const filters: { id: Filter; label: string; description: string }[] = [{ id: "today", label: "Selección de hoy", description: "Las 8 tarjetas más relevantes" }, { id: "all", label: "Todas las tarjetas", description: "Todos los datos disponibles" }, { id: "attention", label: "Necesitan atención", description: "Pendientes y riesgos" }, { id: "healthy", label: "Buenas noticias", description: "Señales positivas" }];

export default function Dashboard() {
  const [filter, setFilter] = useState<Filter>("today"); const [theme, setTheme] = useState<"light" | "dark">("light"); const [themePulse, setThemePulse] = useState(false); const dashboard = useQuery({ queryKey: ["dashboard"], queryFn: fetchDashboard, refetchInterval: 60_000, retry: 2 });
  useEffect(() => { const saved = window.localStorage.getItem("minorte-theme"); if (saved === "light" || saved === "dark") setTheme(saved); }, []);
  const toggleTheme = () => { setTheme((current) => { const next = current === "light" ? "dark" : "light"; window.localStorage.setItem("minorte-theme", next); return next; }); setThemePulse(true); window.setTimeout(() => setThemePulse(false), 480); };
  const cards = useMemo(() => dashboard.data ? buildCards(dashboard.data) : [], [dashboard.data]); const visible = useMemo(() => { const ordered = [...cards].sort((a, b) => b.priority - a.priority); if (filter === "today") return ordered.slice(0, 8); if (filter === "attention") return ordered.filter((card) => card.tone === "urgent" || card.tone === "watch"); if (filter === "healthy") return ordered.filter((card) => card.tone === "positive"); return ordered; }, [cards, filter]); const period = dashboard.data ? displayMonth(dashboard.data.month) : "CARGANDO"; const asOfDate = dashboard.data?.daily.at(-1)?.date ?? (dashboard.data ? `${dashboard.data.month}-01` : ""); const dateLabel = asOfDate ? fullDate.format(new Date(`${asOfDate}T12:00:00Z`)).toUpperCase() : "CARGANDO";
  return <div className={styles.appShell} data-theme={theme}><main className={styles.main}><header className={styles.topbar}><div className={styles.headingGroup}><BanorteLogo/><div className={styles.headingCopy}><p className={styles.overline}>CENTRO FINANCIERO</p><h1>MiNorte</h1><p>Lo más importante de tu negocio, explicado con datos claros.</p></div></div><div className={styles.topActions}><button className={themePulse ? styles.themeButtonPulse : ""} onClick={toggleTheme} aria-label={`Cambiar a modo ${theme === "light" ? "oscuro" : "claro"}`} title={`Modo ${theme === "light" ? "oscuro" : "claro"}`}><Icon name={theme === "light" ? "moon" : "sun"}/></button><span className={styles.datePill}>{dateLabel}</span></div></header><section className={styles.controlPanel} aria-label="Configurar vista de tarjetas"><div><span className={styles.liveDot}/><div><strong>{dashboard.isLoading ? "Conectando datos" : dashboard.isError ? "No se pudo conectar" : "Datos financieros actualizados"}</strong><p>{dashboard.isLoading ? "Consultando el motor financiero…" : dashboard.isError ? "Revisa que la API esté activa en el puerto 8000." : `Información bancaria y fiscal hasta ${period}.`}</p></div></div><div className={styles.filterGroup}>{filters.map((item) => <button key={item.id} className={filter === item.id ? styles.filterActive : ""} onClick={() => setFilter(item.id)} title={item.description} disabled={!dashboard.data}>{item.label}</button>)}</div><div className={styles.count}><strong>{visible.length}</strong><span>visibles de {cards.length}</span></div></section>{dashboard.isError ? <section className={styles.dataError}><h2>No pudimos cargar tus datos</h2><p>La interfaz está lista, pero la API no respondió.</p><button onClick={() => dashboard.refetch()}>Intentar de nuevo</button></section> : null}{dashboard.isLoading ? <section className={styles.loadingGrid} aria-label="Cargando tarjetas"><div/><div/><div/><div/><div/></section> : null}{dashboard.data ? <><section className={styles.galleryHeader}><div><h2>{filters.find((item) => item.id === filter)?.label}</h2><p>Solo mostramos datos calculados por la API financiera.</p></div></section><section className={styles.cardGrid} aria-live="polite">{visible.map((card) => <div key={card.id} id={card.id} className={card.wide ? styles.wide : ""} data-category={card.category} data-priority={card.priority}>{card.node}</div>)}</section></> : null}<footer className={styles.footer}><span>{dashboard.data ? `Datos del motor financiero · ${period}` : "MiNorte · Banorte"}</span><span>El motor calcula. La interfaz explica.</span></footer></main></div>;
}
